<?php

namespace Jet\JustBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PostalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostalRepository extends EntityRepository
{
}